server:
  port: 8081
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://59.110.93.61:3306/edusphere?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: edusphere
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml       # Mapper XML 文件位置
  type-aliases-package: top.ooyyh.edusphere.entity  # 实体类所在包
  global-config:
    db-config:
      id-type: auto       # 主键策略，auto = 自增
      logic-delete-value: 1
      logic-not-delete-value: 0

# 文件上传配置
file:
  upload:
    path: D:/Project/IdeaProjects/EduSphere/uploads/
    image-path: ${file.upload.path}images/
    video-path: ${file.upload.path}videos/
    document-path: ${file.upload.path}documents/
    url-prefix: /uploads/